# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-25 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20190306_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
