# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-06 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='biodata',
            field=models.CharField(max_length=100),
        ),
    ]
