# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-07 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20190306_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='publish',
            field=models.BooleanField(default=True),
        ),
    ]
